# This is a basic workflow to help you get started with Actions

name: Meeshkan tests

# Controls when the action will run.
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  wait-for-vercel-deployment:
    runs-on: ubuntu-18.04
    steps:
      - name: Get deploy url
        run: echo webapp-git-${GITHUB_REF#refs/heads/}-meeshkanml.vercel.app
      - uses: UnlyEd/github-action-await-vercel@v1.1.0
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: webapp-git-dev-1729-set-up-puppeteer-test-meeshkanml.vercel.app
          # deployment-url: "webapp-git-${{ GITHUB_REF#refs/heads/ }}-meeshkanml.vercel.app"
          timeout: 180 # Wait for 3 minutes before failing
      - name: Display deployment status
        run: 'echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}'

  run-jest-puppeteer-tests:
    name: Run the jest-puppeteer tests generated by Meeshkan
    runs-on: ubuntu-18.04
    needs: wait-for-vercel-deployment
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Declare test url
        run: echo "TEST_URL=webapp-git-dev-1729-set-up-puppeteer-test-meeshkanml.vercel.app" >> $GITHUB_ENV
      - name: Clean install package dependencies
        run: yarn
      - name: Run tests
        run: yarn test webapp
