# This is a basic workflow to help you get started with Actions

name: Node CI

# Controls when the action will run.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  wait-for-vercel-deployment:
    runs-on: ubuntu-18.04
    steps:
      - name: Get deploy url
        id: variables
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: UnlyEd/github-action-await-vercel@v1.1.0
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: 'webapp-${{ steps.variables.outputs.sha_short }}-meeshkanml.vercel.app'
          timeout: 20 # Wait for 10 seconds before failing
      - name: Display deployment status
        run: 'echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      #     - name: Clean install package dependencies
      #       run: yarn
      #     - name: Run linter
      #       run: yarn lint
      - name: Run tests
        run: yarn test
